@startuml cartProcess
title Процес створення корзини
start

:Вибрати категорію;

if (чи знайдено необхідні продукти?) then (Так)
  :Показати список;
  :Обрати продукт зі списку;
  :Вказати кількість;
  

else (Ні)
  
  :Показати кнопку нового продукту ;
  :Показати форму нового продукту ;
  :Заповнюємо параметри продукту;
  

endif

' Сюди сходяться всі успішні гілки процесу
:Додати в корзину;
stop
@enduml
  