@startuml createOrder
title Створити замовлення
start

:Створення замовлення зі статусом "В роботі";
:Зарезервувати залишки;

if (Не вистачає товару на складі?) then (Так)
  :Створити заявки на виробництво;
endif
:Завершення процесу створення;
stop
@enduml
