@startuml createProduct
title Процес створення замовлення
start

:Вибрати кліента;
:Вибрати категорію;


if (Потрібно знайти субпродукт для виготовлення?) then (Так)
  :Показати список знайдених субпродуктів;
  :Обрати субпродукт зі списку |


  if (Якщо запасів не вистачає ?) then
     :Створити заявки на виробництво |
  endif

else (Ні)
  ' Явний перехід на логіку простого створення купленого продукту
  :Просте створення (Для куплених продуктів);
endif

' Сюди сходяться всі успішні гілки процесу
:Продовжити (Зберегти продукт);
stop
@enduml
